In [1]:
%pip install pydeseq2

Requirement already satisfied: pydeseq2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (0.5.4)
Requirement already satisfied: anndata>=0.11.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (0.13.3.post0)
Requirement already satisfied: formulaic-contrasts>=0.2.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (1.0.0)
Requirement already satisfied: formulaic>=1.0.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (1.2.2)
Requirement already satisfied: matplotlib>=3.9.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (3.11.2)
Collecting numpy>=2.0.0 (from pydeseq2)
  Downloading numpy-2.5.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.2.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (3.0.5)
Requirement already satisfied: scikit-learn>=1.4.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (1.9.1)
Requirement already satisfied: scipy>=1.12.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydeseq2) (1.17.1)
Requirement already satisfied: array-api-compat>=1.7.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (1.15.0)
Requirement already satisfied: h5py>=3.11 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (3.16.0)
Requirement already satisfied: legacy-api-wrap in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (1.5)
Requirement already satisfied: natsort in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (8.4.0)
Requirement already satisfied: packaging>=24.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (26.3)
Requirement already satisfied: scverse-misc>=0.1.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (0.1.6)
Requirement already satisfied: typing-extensions>=4.16 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (4.16.0)
Requirement already satisfied: zarr>=3.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from anndata>=0.11.0->pydeseq2) (3.4.0)
Requirement already satisfied: interface-meta>=1.2.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from formulaic>=1.0.2->pydeseq2) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from formulaic>=1.0.2->pydeseq2) (2.26.0)
Requirement already satisfied: wrapt>=1.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from formulaic>=1.0.2->pydeseq2) (2.4.1)
Requirement already satisfied: session-info in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from formulaic-contrasts>=0.2.0->pydeseq2) (1.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (1.5.1)
Requirement already satisfied: pillow>=9 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib>=3.9.0->pydeseq2) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.9.0->pydeseq2) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scikit-learn>=1.4.0->pydeseq2) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scikit-learn>=1.4.0->pydeseq2) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from joblib>=1.4.0->scikit-learn>=1.4.0->pydeseq2) (3.1.2)
Requirement already satisfied: session-info2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scverse-misc>=0.1.0->scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (0.4.2)
Requirement already satisfied: pydantic-settings in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (2.15.0)
Requirement already satisfied: python-dotenv in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (1.2.3)
Requirement already satisfied: donfig>=0.8 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from zarr>=3.1->anndata>=0.11.0->pydeseq2) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from zarr>=3.1->anndata>=0.11.0->pydeseq2) (1.8.0)
Requirement already satisfied: msgspec>=0.19 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from zarr>=3.1->anndata>=0.11.0->pydeseq2) (0.21.1)
Requirement already satisfied: numcodecs>=0.14 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from zarr>=3.1->anndata>=0.11.0->pydeseq2) (0.16.5)
Requirement already satisfied: pyyaml in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from donfig>=0.8->zarr>=3.1->anndata>=0.11.0->pydeseq2) (6.0.3)
Requirement already satisfied: pydantic>=2.7.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydantic-settings->scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (2.13.5)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydantic-settings->scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (0.4.4)
Requirement already satisfied: annotated-types>=0.6.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydantic>=2.7.0->pydantic-settings->scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pydantic>=2.7.0->pydantic-settings->scverse-misc[settings]>=0.1.0->anndata>=0.11.0->pydeseq2) (2.46.5)
Requirement already satisfied: stdlib_list in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from session-info->formulaic-contrasts>=0.2.0->pydeseq2) (0.12.0)
Downloading numpy-2.5.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 113.9 MB/s  0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scispacy 0.6.2 requires numpy<2.0, but you have numpy 2.5.3 which is incompatible.
Successfully installed numpy-2.5.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from seaborn) (2.5.3)
Requirement already satisfied: pandas>=1.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install archs4py

Collecting archs4py
  Downloading archs4py-1.0.4.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: h5py in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from archs4py) (3.16.0)
Requirement already satisfied: numpy in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from archs4py) (2.5.3)
Requirement already satisfied: pandas in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from archs4py) (3.0.5)
Collecting qnorm (from archs4py)
  Downloading qnorm-0.9.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: setuptools in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from archs4py) (84.0.0)
Requirement already satisfied: tqdm in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from archs4py) (4.70.1)
Collecting wget (from archs4py)
  Downloading wget-3.2.zip (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting s3fs (from archs4py)
  Downloading s3fs-2026.7.0-py3-none-any.whl.metadata (1.2 kB)
Collecting biomart (from archs4py)
  Downloading biomart-0.9.2-py3-none-any.whl.metadata (3.3 kB)
Collecting xalign (from archs4py)
  Downloading xalign-0.1.75.tar.gz (6.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 21.4 MB/s  0:00:00 18.5 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests>=2.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from biomart->archs4py) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from requests>=2.2->biomart->archs4py) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from requests>=2.2->biomart->archs4py) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from requests>=2.2->biomart->archs4py) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from requests>=2.2->biomart->archs4py) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from pandas->archs4py) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->archs4py) (1.17.0)
Requirement already satisfied: numba in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from qnorm->archs4py) (0.67.0)
Requirement already satisfied: llvmlite<0.50,>=0.49.0dev0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from numba->qnorm->archs4py) (0.49.0)
Collecting aiobotocore<4.0.0,>=2.19.0 (from s3fs->archs4py)
  Downloading aiobotocore-3.9.1-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: fsspec<2026.7.1,>=2026.7.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from s3fs->archs4py) (2026.7.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 (from s3fs->archs4py)
  Downloading aiohttp-3.14.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting aioitertools<1.0.0,>=0.5.1 (from aiobotocore<4.0.0,>=2.19.0->s3fs->archs4py)
  Downloading aioitertools-0.13.0-py3-none-any.whl.metadata (3.3 kB)
Collecting botocore<1.43.76,>=1.43.66 (from aiobotocore<4.0.0,>=2.19.0->s3fs->archs4py)
  Downloading botocore-1.43.75-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from aiobotocore<4.0.0,>=2.19.0->s3fs->archs4py)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting multidict<7.0.0,>=6.0.0 (from aiobotocore<4.0.0,>=2.19.0->s3fs->archs4py)
  Downloading multidict-6.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->archs4py) (2.4.1)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py)
  Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py)
  Downloading propcache-0.5.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (25 kB)
Requirement already satisfied: typing_extensions>=4.4 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py) (4.16.0)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs->archs4py)
  Downloading yarl-1.25.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (111 kB)
Requirement already satisfied: scikit-learn in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from xalign->archs4py) (1.9.1)
Collecting progress (from xalign->archs4py)
  Downloading progress-1.6.1-py3-none-any.whl.metadata (4.3 kB)
Collecting loess (from xalign->archs4py)
  Downloading loess-2.2.0-py3-none-any.whl.metadata (13 kB)
Collecting statsmodels (from xalign->archs4py)
  Downloading statsmodels-0.15.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting mygene (from xalign->archs4py)
  Downloading mygene-3.2.2-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: matplotlib in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from loess->xalign->archs4py) (3.11.2)
Collecting plotbin (from loess->xalign->archs4py)
  Downloading plotbin-3.2.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: contourpy>=1.0.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (26.3)
Requirement already satisfied: pillow>=9 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from matplotlib->loess->xalign->archs4py) (3.3.2)
Collecting biothings-client>=0.2.6 (from mygene->xalign->archs4py)
  Downloading biothings_client-0.5.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: httpx<1.0,>=0.25.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from biothings-client>=0.2.6->mygene->xalign->archs4py) (0.28.1)
Requirement already satisfied: anyio in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from httpx<1.0,>=0.25.0->biothings-client>=0.2.6->mygene->xalign->archs4py) (4.15.1)
Requirement already satisfied: httpcore==1.* in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from httpx<1.0,>=0.25.0->biothings-client>=0.2.6->mygene->xalign->archs4py) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0,>=0.25.0->biothings-client>=0.2.6->mygene->xalign->archs4py) (0.16.0)
Requirement already satisfied: scipy in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from plotbin->loess->xalign->archs4py) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scikit-learn->xalign->archs4py) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scikit-learn->xalign->archs4py) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from scikit-learn->xalign->archs4py) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from joblib>=1.4.0->scikit-learn->xalign->archs4py) (3.1.2)
Collecting patsy>=0.5.6 (from statsmodels->xalign->archs4py)
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: formulaic>=1.1.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from statsmodels->xalign->archs4py) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /home/vik/bridge-rna/jupyter-env/lib/python3.12/site-packages (from formulaic>=1.1.0->statsmodels->xalign->archs4py) (2.0.1)
Downloading biomart-0.9.2-py3-none-any.whl (12 kB)
Downloading qnorm-0.9.0-py3-none-any.whl (14 kB)
Downloading s3fs-2026.7.0-py3-none-any.whl (32 kB)
Downloading aiobotocore-3.9.1-py3-none-any.whl (102 kB)
Downloading aiohttp-3.14.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 113.1 MB/s  0:00:00
Downloading aioitertools-0.13.0-py3-none-any.whl (24 kB)
Downloading botocore-1.43.75-py3-none-any.whl (15.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 161.7 MB/s  0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading multidict-6.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (287 kB)
Downloading yarl-1.25.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (117 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
Downloading propcache-0.5.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (250 kB)
Downloading loess-2.2.0-py3-none-any.whl (19 kB)
Downloading mygene-3.2.2-py2.py3-none-any.whl (5.4 kB)
Downloading biothings_client-0.5.1-py3-none-any.whl (52 kB)
Downloading plotbin-3.2.0-py3-none-any.whl (19 kB)
Downloading progress-1.6.1-py3-none-any.whl (9.8 kB)
Downloading statsmodels-0.15.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 153.2 MB/s  0:00:00
Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
Building wheels for collected packages: archs4py, wget, xalign
  Building wheel for archs4py (pyproject.toml) ... done
  Created wheel for archs4py: filename=archs4py-1.0.4-py3-none-any.whl size=18502 sha256=6288b611306e633daf1ba71e8d5d44c9d3d9f62f9c4ba04670255caa4e94ddb1
  Stored in directory: /home/vik/.cache/pip/wheels/86/61/c7/0e4580ce6350339f0ac5915c8e1b3c2b9481f98142612be521
  Building wheel for wget (pyproject.toml) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9686 sha256=f1406322dbf64f6c9814038b38bc03244366f30afdbb8aee7431cf56c4f065ba
  Stored in directory: /home/vik/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
  Building wheel for xalign (pyproject.toml) ... done
  Created wheel for xalign: filename=xalign-0.1.75-py3-none-any.whl size=6053355 sha256=c8493f75124377a85e051bcc661911e4b345244ae6ad60cc64edc56b4c767b9e
  Stored in directory: /home/vik/.cache/pip/wheels/89/91/23/16753b19932f2b8af04c488cd0a0fdaece501d7fc1e8c12dda
Successfully built archs4py wget xalign
Installing collected packages: wget, propcache, progress, patsy, multidict, jmespath, frozenlist, aioitertools, aiohappyeyeballs, yarl, qnorm, botocore, biomart, aiosignal, plotbin, biothings-client, aiohttp, statsmodels, mygene, loess, aiobotocore, xalign, s3fs, archs4py
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24/24 [archs4py] 21/24 [xalign]dels]tp]s]
Successfully installed aiobotocore-3.9.1 aiohappyeyeballs-2.7.1 aiohttp-3.14.3 aioitertools-0.13.0 aiosignal-1.4.0 archs4py-1.0.4 biomart-0.9.2 biothings-client-0.5.1 botocore-1.43.75 frozenlist-1.8.0 jmespath-1.1.0 loess-2.2.0 multidict-6.8.0 mygene-3.2.2 patsy-1.0.3 plotbin-3.2.0 progress-1.6.1 propcache-0.5.4 qnorm-0.9.0 s3fs-2026.7.0 statsmodels-0.15.0 wget-3.2 xalign-0.1.75 yarl-1.25.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
%wget https://s3.k8s.maayanlab.cloud/archs4/files/human_gene_v2.latest.h5

UsageError: Line magic function `%wget` not found.

In [3]:
#imports
from pathlib import Path
import pandas as pd
import archs4py as a4
from pydeseq2.dds import DeseqDataSet
from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#load ground control and space flight from specified cohort (copy from cluster_metadata)

def get_counts_metadata(cohort_name,clist): #returns counts and metadata dataframes
    human_archs4_path = '/media/volume/H5-Files/archs4/human_gene_v2.latest.h5'
    mouse_archs4_path = '/home/vik/bridge-rna/archs4h5/mouse_gene_v2.5.h5'
    folder = Path.cwd().parent / "archs4data"/ "archs4metadata_cohort_noncbi"
    full_name = folder / f"{cohort_name}_hits.csv"
    ch_df = pd.read_csv(full_name)
    
    #select GSM,spaceflight
    metadata = ch_df[['gsm','spaceflight']]
    metadata = metadata.groupby('gsm').filter(lambda x : len(x)<2) #drop samples that appear in ground and space
    metadata = metadata.set_index("gsm")
    metadata.index.name = None
    metadata = metadata[metadata['spaceflight'].isin(clist)]
    metadata = metadata.sort_index()
    

    #get counts
    gsms = metadata.index.tolist()
    #print(gsms)
    #gsm may be in human or mouse. but would they ever be mixed human and mouse?
    #for now just try mouse and if it fails then go human
    
    sample_counts = a4.data.samples(mouse_archs4_path,gsms)
    if sample_counts.empty:
        print("Human isn't downloaded yet")
        raise ValueError("Human isn't downloaded yet")
        sample_counts = a4.data.samples(human_archs4_path,gsms)
    sample_counts = sample_counts.groupby(sample_counts.index).agg(func='sum') #collapses all the dupes
    sample_counts = sample_counts.T
    sample_counts = sample_counts.sort_index()
    
    
    
    return sample_counts,metadata

In [85]:

cohort = 'OSD-667'
counts_df,metadata_df = get_counts_metadata(cohort,['Ground Control','Space Flight'])

100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 32.38it/s]

In [86]:
metadata_df["spaceflight"] = pd.Categorical(
    metadata_df["spaceflight"],
    categories=["Ground Control", "Space Flight"],
    ordered=True
)

In [87]:
counts_df

,0610005C13Rik,0610006L08Rik,0610009B22Rik,0610009E02Rik,0610009L18Rik,0610010K14Rik,0610012D04Rik,0610012G03Rik,0610025J13Rik,0610030E20Rik,...,n-R5s58,n-R5s60,n-R5s64,n-R5s65,n-R5s7,n-R5s71,n-R5s86,n-R5s88,n-R5s92,n-R5s93
GSM2593658,154,0,120,24,41,166,6,453,2,491,...,0,0,0,0,0,0,0,0,0,0
GSM2593665,93,0,127,30,59,184,8,549,0,512,...,0,0,0,0,0,0,0,0,0,0
GSM2593668,82,0,129,27,54,210,5,568,0,540,...,0,0,0,0,0,0,0,0,0,0
GSM2950654,98,0,95,14,22,138,7,376,0,461,...,0,0,0,0,0,0,0,0,0,0
GSM2950660,176,0,111,29,37,153,7,382,2,464,...,0,0,0,0,0,0,0,0,0,0
GSM2950672,194,0,138,26,31,169,6,417,1,482,...,0,0,0,0,0,0,0,0,0,0

In [88]:
counts_df.columns[counts_df.columns.duplicated()]

Index([], dtype='str')

In [89]:
metadata_df.index.tolist()

['GSM2593658',
 'GSM2593665',
 'GSM2593668',
 'GSM2950654',
 'GSM2950660',
 'GSM2950672']

In [90]:
metadata_df

               spaceflight
GSM2593658  Ground Control
GSM2593665    Space Flight
GSM2593668    Space Flight
GSM2950654  Ground Control
GSM2950660  Ground Control
GSM2950672    Space Flight

In [91]:
#load them into the deseq format
inference = DefaultInference(n_cpus=8)
dds = DeseqDataSet(
    counts=counts_df,
    metadata=metadata_df,
    design="spaceflight",  # compare samples based on the "condition"
    # column ("B" vs "A")
    refit_cooks=True,
    inference=inference,
)

In [92]:
'''
Size factors: Scaling factors, for normalization
Genewise dispersions: variability in each gene's counts accross replicates
Replicate: samples with the same condition (i.e Ground)
Trend Coeff: Dispersion-mean trend (smooth curve). The coeffs are the coeffs for the parametric model
*for DE Analysis, it is not necessary to use gene lengths to estimate the scaling factors (it is even not recommended) (i.e typical normalization methods)
Deseq uses a different normalization method
MAP dispersion: applies shrinkage; uses Bayes empirical shrinkage
LFC: Log fold change

'''

"\nSize factors: Scaling factors, for normalization\nGenewise dispersions: variability in each gene's counts accross replicates\nReplicate: samples with the same condition (i.e Ground)\nTrend Coeff: Dispersion-mean trend (smooth curve). The coeffs are the coeffs for the parametric model\n*for DE Analysis, it is not necessary to use gene lengths to estimate the scaling factors (it is even not recommended) (i.e typical normalization methods)\nDeseq uses a different normalization method\nMAP dispersion: applies shrinkage; uses Bayes empirical shrinkage\nLFC: Log fold change\n\n"

In [93]:
dds.fit_size_factors() 
dds.obs["size_factors"]

Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.03 seconds.

GSM2593658    1.007989
GSM2593665    1.205046
GSM2593668    1.100642
GSM2950654    0.854391
GSM2950660    0.947468
GSM2950672    0.951356
Name: size_factors, dtype: float64

In [ ]:
dds.fit_genewise_dispersions()
dds.var["genewise_dispersions"]

In [ ]:
dds.fit_dispersion_trend()
dds.uns["trend_coeffs"]
dds.var["fitted_dispersions"]

In [ ]:
dds.fit_dispersion_prior()
print(
    f"logres_prior={dds.uns['_squared_logres']}, sigma_prior={dds.uns['prior_disp_var']}"
)

In [ ]:
dds.fit_MAP_dispersions()
dds.var["MAP_dispersions"]
dds.var["dispersions"]

In [ ]:
dds.fit_LFC()
dds.varm["LFC"]

In [ ]:
dds.calculate_cooks()
if dds.refit_cooks:
    # Replace outlier counts
    dds.refit()

In [ ]:
ds = DeseqStats(
    dds,
    contrast=["spaceflight", "Space Flight", "Ground Control"],
    alpha=0.05,
    cooks_filter=True,
    independent_filter=True,
)

In [ ]:
ds.run_wald_test()
ds.p_values

In [ ]:
ds.summary()

In [ ]:
#visualization 
df = ds.results_df

In [ ]:
df.columns

In [ ]:
#save summary to folder

df.to_csv(f"deseq_summaries/{cohort}",index=True)

In [ ]:
#test load
read_cohort = 'OSD-667'
loaded_df = pd.read_csv(f'deseq_summaries/{read_cohort}',index_col=0)

In [ ]:
loaded_df

In [ ]:
#pydeseq2 imports are not working, this is a direct copy paste of their function
from typing import Literal
def make_MA_plot(
    results_df: pd.DataFrame,
    padj_thresh: float = 0.05,
    log: bool = True,
    save_path: str | None = None,
    lfc_null: float = 0,
    alt_hypothesis: Literal["greaterAbs", "lessAbs", "greater", "less"] | None = None,
    **kwargs,
) -> None:
    """
    Create an log ratio (M)-average (A) plot using matplotlib.

    Useful for looking at log fold-change versus mean expression between two groups/samples/etc.
    Uses matplotlib to emulate the ``make_MA()`` function in DESeq2 in R.

    Parameters
    ----------
    results_df
        Resultant dataframe after running DeseqStats() and .summary().
    padj_thresh
        P-value threshold to subset scatterplot colors on.
    log
        Whether or not to log scale features and targets axes (``default=True``).
    save_path
        The path where to save the plot.
        If left None, the plot won't be saved (``default=None``).
    lfc_null
        The (log2) log fold change under the null hypothesis. (default: ``0``).
    alt_hypothesis
        The alternative hypothesis for computing wald p-values. (default: ``None``).
    **kwargs
        Matplotlib keyword arguments for the scatter plot.
    """
    colors = results_df["padj"].apply(lambda x: "darkred" if x < padj_thresh else "gray")

    fig, ax = plt.subplots(dpi=600)

    # Set default alpha and s parameters, if not already specified
    kwargs.setdefault("alpha", 0.5)
    kwargs.setdefault("s", 0.2)

    plt.scatter(
        x=results_df["baseMean"],
        y=results_df["log2FoldChange"],
        c=colors,
        **kwargs,
    )

    ax.set_adjustable("datalim")

    if log is True:
        plt.xscale("log")

    plt.xlabel("mean of normalized counts")
    plt.ylabel("log2 fold change")
    plt.title(f"MA Plot: {read_cohort} Ground Control ARCHS4 Hits vs Spaceflight ARCHS4 Hits")

    plt.axhline(lfc_null, color="red", alpha=0.5, linestyle="--", zorder=3)
    if alt_hypothesis and alt_hypothesis in ["greaterAbs", "lessAbs"]:
        plt.axhline(-lfc_null, color="red", alpha=0.5, linestyle="--", zorder=3)
    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, bbox_inches="tight")

In [ ]:
make_MA_plot(loaded_df)

In [ ]:
##gsea?###